export const trainers = [
  {
    id: "3zejR8Dq7d",
    name: "김나영",
    position: "선생님",
    gymName: "부평 스페시맨GYM",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/3zejR8Dq7d+2S62Equ9sMhr98e9byoB8.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "kwAYxwYt9",
    name: "정덕영",
    position: "선생님",
    gymName: "부평 스페시맨GYM",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/kwAYxwYt9+eGn6rDdnTbJpcWkuGuc.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "wLD2Nqmut",
    name: "문정욱",
    position: "선생님",
    gymName: "부평 스페시맨GYM",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/wLD2Nqmut+KqE7DdMjVYLdNy8YTEL.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "2JVD2Vh43Y",
    name: "손은혁",
    position: "선생님",
    gymName: "부평 스페시맨GYM",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/2JVD2Vh43Y+2QkT8m1iDF9RJobPdZVHh.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 5,
    reviewCount: 2,
  },
  {
    id: "4XHVVAcgnL",
    name: "김현민",
    position: "선생님",
    gymName: "부평 스페시맨GYM",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/4XHVVAcgnL+2QUHBYE8CBLXAzcaScqxT.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "gXD3oEBpe",
    name: "장중구",
    position: "선생님",
    gymName: "부평 스페시맨GYM",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/gXD3oEBpe+2SPfu6hKpicdujh2UioEK.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "4iYoRW3sZc",
    name: "최어진",
    position: "선생님",
    gymName: "부평 PT의정석 운동재활센터",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/4iYoRW3sZc+FExgy8m8d5Fh.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "3jxCjJF8bo",
    name: "홍기재",
    position: "선생님",
    gymName: "부평 키워드핏",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/3jxCjJF8bo+2P9p3d96VFvKEswXZ7mHu.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "27SpNQMw5E",
    name: "전성균",
    position: "선생님",
    gymName: "부평 키워드핏",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/27SpNQMw5E+2SPJfD6xg6pBmQ3kjqyZK.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "qW5xiVpxP",
    name: "최재혁",
    position: "선생님",
    gymName: "부평 키워드핏",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/qW5xiVpxP+2NrxhNKLmFB2qt58HiUnU.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "25nDAHUQHd",
    name: "김태원",
    position: "선생님",
    gymName: "부평 PT시작",
    gymAddress: "인천 부평구 부평동",
    profileImage:
      "https://api.da-gym.net/trainers/images/25nDAHUQHd+2QTAiPejQiyUZN5GXQaFF.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 5,
    reviewCount: 1,
  },
  {
    id: "26tdtAZ8DY",
    name: "이창덕",
    position: "선생님",
    gymName: "일신 엘케이짐",
    gymAddress: "인천 부평구 일신동",
    profileImage:
      "https://api.da-gym.net/trainers/images/26tdtAZ8DY+98B2aJwL4ET.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "4hiyTTXSWv",
    name: "황민지",
    position: "선생님",
    gymName: "송내 짐에스헬스장",
    gymAddress: "경기 부천시 송내동",
    profileImage:
      "https://api.da-gym.net/trainers/images/4hiyTTXSWv+jRY2gLQRK1e.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: false,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "3WDS3Dxyg3",
    name: "육아진",
    position: "선생님",
    gymName: "삼산 별필라테스&플라잉요가 ",
    gymAddress: "인천 부평구 삼산동",
    profileImage:
      "https://api.da-gym.net/trainers/images/3WDS3Dxyg3+7kSXbCpZJS.jpg",
    exerciseTypes: ["기구필라테스"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "29Rr7vadNm",
    name: "오혜진",
    position: "선생님",
    gymName: "삼산 별필라테스&플라잉요가 ",
    gymAddress: "인천 부평구 삼산동",
    profileImage:
      "https://api.da-gym.net/trainers/images/29Rr7vadNm+UC92Q4UN7Gya.jpg",
    exerciseTypes: ["기구필라테스"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "4kcKef9V5u",
    name: "이보영",
    position: "선생님",
    gymName: "상동 디에이트짐&필라테스",
    gymAddress: "경기 부천시 상동",
    profileImage:
      "https://api.da-gym.net/trainers/images/4kcKef9V5u+JzYnd9YSrPt.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "2QANBD587i",
    name: "현준",
    position: "선생님",
    gymName: "만수 엑스포스짐",
    gymAddress: "인천 남동구 만수동",
    profileImage:
      "https://api.da-gym.net/trainers/images/2QANBD587i+QyJjV2FzruRG.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "iueGwVQbG",
    name: "현주",
    position: "선생님",
    gymName: "만수 엑스포스짐",
    gymAddress: "인천 남동구 만수동",
    profileImage:
      "https://api.da-gym.net/trainers/images/iueGwVQbG+2QV15fuAbDdJpg9MaSzYs.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 5,
    reviewCount: 1,
  },
  {
    id: "uPAiixYUm",
    name: "우다솔",
    position: "선생님",
    gymName: "상동 다니엘짐",
    gymAddress: "경기 부천시 상동",
    profileImage:
      "https://api.da-gym.net/trainers/images/uPAiixYUm+2QVSu6bCLJp8VguPm7ZDF.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "cWewhd8HK",
    name: "고기웅",
    position: "선생님",
    gymName: "부천시청 라인제작소 3호점 24시",
    gymAddress: "경기 부천시 중동",
    profileImage:
      "https://api.da-gym.net/trainers/images/cWewhd8HK+UHA4jBaa19Je.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
];
